# project LaserBoy
# James Lehman
# laserboy.org

RM       = rm -f
CPP      = g++
INC      = -I/opt/local/include
LIB      = -L/opt/local/lib
LIBS     = -lSDL2 -lSDL2Main -lboost_filesystem -lboost_system -lpthread -framework Cocoa

CPPFLAGS = -D__WITH_SDL2__ \
           -std=c++17 \
           -O3 \
           -msse2 \
           -mfpmath=sse \
           -Wall \
           -Wextra \
           -frounding-math \
           -fsignaling-nans \
           -Wno-unused-parameter \
           -Wno-implicit-fallthrough \
           -Wno-missing-field-initializers \
           -Wno-misleading-indentation \
           -Wno-unused-but-set-variable \
           -Wno-mismatched-new-delete \
           -fexpensive-optimizations \
           -static \
           $(INC) \
           $(LIB) \
           $(LIBS)

HEADERS   = LaserBoy_includes.hpp \
            LaserBoy_macros.hpp \
            LaserBoy_common.hpp \
            LaserBoy_utility.hpp \
            LaserBoy_oscillator.hpp \
            LaserBoy_font.hpp \
            LaserBoy_bmp.hpp \
            LaserBoy_3D_short.hpp \
            LaserBoy_color.hpp \
            LaserBoy_vertex.hpp \
            LaserBoy_segment.hpp \
            LaserBoy_3D_double.hpp \
            LaserBoy_real_vertex.hpp \
            LaserBoy_real_segment.hpp \
            LaserBoy_real_segment_set.hpp \
            LaserBoy_ild_header.hpp \
            LaserBoy_frame.hpp \
            LaserBoy_frame_set.hpp \
            LaserBoy_palette.hpp \
            LaserBoy_palette_set.hpp \
            LaserBoy_wave.hpp \
            LaserBoy_SDL_GUI.hpp \
            LaserBoy_space.hpp \
            LaserBoy_TUI.hpp

OBJ      = ../build/LaserBoy.osx \
           ../build/LaserBoy_common.osx \
           ../build/LaserBoy_oscillator.osx \
           ../build/LaserBoy_frame.osx \
           ../build/LaserBoy_frame_effects.osx \
           ../build/LaserBoy_selected_frames_effects.osx \
           ../build/LaserBoy_frame_set.osx \
           ../build/LaserBoy_frame_set_effects.osx \
           ../build/LaserBoy_ild_header.osx \
           ../build/LaserBoy_segment.osx \
           ../build/LaserBoy_palette.osx \
           ../build/LaserBoy_palette_set.osx \
           ../build/LaserBoy_real_segment.osx \
           ../build/LaserBoy_real_segment_set.osx \
           ../build/LaserBoy_wave.osx \
           ../build/LaserBoy_space.osx \
           ../build/LaserBoy_TUI.osx \
           ../build/LaserBoy_SDL_GUI.osx \
           ../build/LaserBoy_bmp.osx \
           ../build/LaserBoy_font.osx

BIN      = ../LaserBoy

all: $(BIN) strip

strip:
	$(STRIP) $(BIN)

clean:
	$(RM) $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(OBJ) -o $(BIN) $(LIB) $(LIBS)

../build/LaserBoy.osx: LaserBoy.cpp $(HEADERS)
	$(CPP) -c LaserBoy.cpp -o ../build/LaserBoy.osx $(CPPFLAGS)

../build/LaserBoy_SDL_GUI.osx: LaserBoy_SDL_GUI.cpp $(HEADERS)
	$(CPP) -c LaserBoy_SDL_GUI.cpp -o ../build/LaserBoy_SDL_GUI.osx $(CPPFLAGS)

../build/LaserBoy_TUI.osx: LaserBoy_TUI.cpp $(HEADERS)
	$(CPP) -c LaserBoy_TUI.cpp -o ../build/LaserBoy_TUI.osx $(CPPFLAGS)

../build/LaserBoy_space.osx: LaserBoy_space.cpp $(HEADERS)
	$(CPP) -c LaserBoy_space.cpp -o ../build/LaserBoy_space.osx $(CPPFLAGS)

../build/LaserBoy_frame_set_effects.osx: LaserBoy_frame_set_effects.cpp $(HEADERS)
	$(CPP) -c LaserBoy_frame_set_effects.cpp -o ../build/LaserBoy_frame_set_effects.osx $(CPPFLAGS)

../build/LaserBoy_selected_frames_effects.osx: LaserBoy_selected_frames_effects.cpp $(HEADERS)
	$(CPP) -c LaserBoy_selected_frames_effects.cpp -o ../build/LaserBoy_selected_frames_effects.osx $(CPPFLAGS)

../build/LaserBoy_frame_effects.osx: LaserBoy_frame_effects.cpp $(HEADERS)
	$(CPP) -c LaserBoy_frame_effects.cpp -o ../build/LaserBoy_frame_effects.osx $(CPPFLAGS)

../build/LaserBoy_palette_set.osx: LaserBoy_palette_set.cpp $(HEADERS)
	$(CPP) -c LaserBoy_palette_set.cpp -o ../build/LaserBoy_palette_set.osx $(CPPFLAGS)

../build/LaserBoy_palette.osx: LaserBoy_palette.cpp $(HEADERS)
	$(CPP) -c LaserBoy_palette.cpp -o ../build/LaserBoy_palette.osx $(CPPFLAGS)

../build/LaserBoy_frame_set.osx: LaserBoy_frame_set.cpp $(HEADERS)
	$(CPP) -c LaserBoy_frame_set.cpp -o ../build/LaserBoy_frame_set.osx $(CPPFLAGS)

../build/LaserBoy_frame.osx: LaserBoy_frame.cpp $(HEADERS)
	$(CPP) -c LaserBoy_frame.cpp -o ../build/LaserBoy_frame.osx $(CPPFLAGS)

../build/LaserBoy_ild_header.osx: LaserBoy_ild_header.cpp LaserBoy_ild_header.hpp LaserBoy_common.hpp LaserBoy_macros.hpp LaserBoy_includes.hpp
	$(CPP) -c LaserBoy_ild_header.cpp -o ../build/LaserBoy_ild_header.osx $(CPPFLAGS)

../build/LaserBoy_bmp.osx: LaserBoy_bmp.cpp LaserBoy_bmp.hpp LaserBoy_font.hpp LaserBoy_color.hpp LaserBoy_common.hpp LaserBoy_macros.hpp LaserBoy_includes.hpp
	$(CPP) -c LaserBoy_bmp.cpp -o ../build/LaserBoy_bmp.osx $(CPPFLAGS)

../build/LaserBoy_font.osx: LaserBoy_font.cpp LaserBoy_font.hpp
	$(CPP) -c LaserBoy_font.cpp -o ../build/LaserBoy_font.osx $(CPPFLAGS)

../build/LaserBoy_segment.osx: LaserBoy_segment.cpp $(HEADERS)
	$(CPP) -c LaserBoy_segment.cpp -o ../build/LaserBoy_segment.osx $(CPPFLAGS)

../build/LaserBoy_real_segment.osx: LaserBoy_real_segment.cpp $(HEADERS)
	$(CPP) -c LaserBoy_real_segment.cpp -o ../build/LaserBoy_real_segment.osx $(CPPFLAGS)

../build/LaserBoy_real_segment_set.osx: LaserBoy_real_segment_set.cpp $(HEADERS)
	$(CPP) -c LaserBoy_real_segment_set.cpp -o ../build/LaserBoy_real_segment_set.osx $(CPPFLAGS)

../build/LaserBoy_wave.osx: LaserBoy_wave.cpp LaserBoy_wave.hpp LaserBoy_common.hpp LaserBoy_macros.hpp LaserBoy_includes.hpp
	$(CPP) -c LaserBoy_wave.cpp -o ../build/LaserBoy_wave.osx $(CPPFLAGS)

../build/LaserBoy_oscillator.osx: LaserBoy_oscillator.cpp LaserBoy_oscillator.hpp LaserBoy_common.hpp LaserBoy_includes.hpp
	$(CPP) -c LaserBoy_oscillator.cpp -o ../build/LaserBoy_oscillator.osx $(CPPFLAGS)

../build/LaserBoy_common.osx: LaserBoy_common.cpp LaserBoy_common.hpp LaserBoy_macros.hpp LaserBoy_includes.hpp
	$(CPP) -c LaserBoy_common.cpp -o ../build/LaserBoy_common.osx $(CPPFLAGS)
